# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Meghedi Tarvirdians"
title_separator          : "-"
name                     : &name "Meghedi Tarvirdians"
description              : "English teacher based in Armenia."
url                      : https://meghedit.github.io
baseurl                  : ""
repository               : "meghedit/meghedit.github.io"

# Site Author (controls the sidebar)
author:
  avatar           : "profile.png"
  name             : "Meghedi Tarvirdians"
  pronouns         : "she/her"
  bio              : "English Teacher"
  location         : "Armenia"
  email            : "tarverdian.mt@gmail.com"
  uri              : "https://www.italki.com/en/teacher/her-profile-link"
  linkedin         : "meghedi-tarvirdians-b81956250"
